#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

if (( $EUID == 0 )); then
    CONFIG="root.conf.yaml"
else
    git -C dotbot submodule sync --quiet --recursive
    git submodule update --init --recursive dotbot
    git submodule update --init --recursive crontab-dotbot
fi

"${BASEDIR}/dotbot/bin/dotbot" -d "${BASEDIR}" --plugin-dir crontab-dotbot -c "${CONFIG}" "${@}"

