#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C dotbot submodule sync --quiet --recursive
git submodule update --init --recursive dotbot
git submodule update --init --recursive crontab-dotbot
git submodule update --init --recursive dotbot-yay

"${BASEDIR}/dotbot/bin/dotbot" -d "${BASEDIR}" -p dotbot-yay/yay.py --plugin-dir crontab-dotbot -c "${CONFIG}" "${@}"

