#!/bin/bash
if [ -d "$ZSH" ]; then
    echo "ohmyzsh is installed"
else
    
    if ! command -v zsh > /dev/null
    then
        echo Install zsh first!
        exit
    fi
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

export PLUGINS=~/.oh-my-zsh/custom/plugins

echo Installing zsh-autosuggestions
git -C $PLUGINS/zsh-autosuggestions pull &> /dev/null || git clone -q https://github.com/zsh-users/zsh-autosuggestions $PLUGINS/zsh-autosuggestions
echo Installing zsh-syntax-highlighting
git -C $PLUGINS/zsh-syntax-highlighting pull &> /dev/null || git clone -q https://github.com/zsh-users/zsh-syntax-highlighting.git $PLUGINS/zsh-syntax-highlighting
echo Installing zsh-histdb
git -C $PLUGINS/zsh-histdb pull &> /dev/null || git clone -q https://github.com/larkery/zsh-histdb.git $PLUGINS/zsh-histdb

export THEMES=~/.oh-my-zsh/custom/themes

echo Installing powerlevel10k
git -C $THEMES/powerlevel10k pull &> /dev/null || git clone -q https://github.com/romkatv/powerlevel10k.git $THEMES/powerlevel10k

