#! /bin/sh


xsetroot -cursor_name left_ptr
setxkbmap -option ctrl:nocaps
export GTK_THEME=Adwaita:dark

if [ "$(hostname)" = "sam-desktop" ]
then
    bspc monitor DP-0 -d 3 4 5 6 7 8 9
    bspc monitor HDMI-0 -d 1 2
    
    xrandr --output DP-0 --auto --output HDMI-0 --auto --left-of DP-0
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         1
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true



# Polybar
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    pgrep -x polybar > /dev/null || 2>/dev/null 1>/dev/null MONITOR=$m polybar --config=~/.config/polybar/polybar.ini --reload  &
done

pgrep -x clipit > /dev/null || 2>/dev/null 1>/dev/null clipit -d  &
pgrep -x mconnect > /dev/null || 2>/dev/null 1>/dev/null mconnect -d  &
2>/dev/null 1>/dev/null bspwm-focus  &

# feh --no-fehbg --bg-center ~/Dotfiles/wallpaper.png
feh --bg-center ~/Downloads/windows-10.jpg

launch sxhkd
launch dunst
launch schildichat schildichat-desktop
launch armcord

bspc rule -a "Jellyfin Media Player" desktop=^10
bspc rule -a FreeTube desktop=^10
bspc rule -a thunderbird desktop=^7
bspc rule -a "Minecraft 1.12.2" desktop=^9
bspc rule -a Joplin desktop=^6
bspc rule -a kitty desktop=^5
bspc rule -a Code desktop=^4
bspc rule -a LibreWolf desktop=^3
bspc rule -a ArmCord desktop=^2
bspc rule -a SchildiChat desktop=^1
