#! /bin/sh


xsetroot -cursor_name left_ptr


bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true



# Polybar
pgrep -x polybar > /dev/null || 2>/dev/null 1>/dev/null polybar --config=~/.config/polybar/polybar.ini --reload  &
pgrep -x clipit > /dev/null || 2>/dev/null 1>/dev/null clipit -d  &

# feh --no-fehbg --bg-center ~/Dotfiles/wallpaper.png
feh --no-fehbg --bg-center ~/Downloads/windows-10.jpg
picom --config ~/.config/picom/picom.conf --backend xrender &

launch sxhkd
launch dunst
# launch kitty
# launch code
# launch chromium
# launch discord
# launch schildichat-desktop


bspc rule -a kitty desktop=^5
bspc rule -a Code desktop=^4
bspc rule -a Chromium desktop=^3
bspc rule -a WebCord desktop=^2
bspc rule -a SchildiChat desktop=^1
