#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &






## Polybar
killall polybar

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload --config=${HOME}/.config/polybar/config bar &
  done
else
  polybar --reload --config=${HOME}/.config/polybar/config bar &
fi


bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --no-fehbg --bg-center Dotfiles/wallpaper.png